// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_new_optimization_problem
SEXP rcpp_new_optimization_problem(std::size_t nrow, std::size_t ncol, std::size_t ncell);
RcppExport SEXP _prioriactions_rcpp_new_optimization_problem(SEXP nrowSEXP, SEXP ncolSEXP, SEXP ncellSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::size_t >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< std::size_t >::type ncell(ncellSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_new_optimization_problem(nrow, ncol, ncell));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_optimization_problem_as_list
Rcpp::List rcpp_optimization_problem_as_list(SEXP x);
RcppExport SEXP _prioriactions_rcpp_optimization_problem_as_list(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_optimization_problem_as_list(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_optimization_problem_ncol
std::size_t rcpp_get_optimization_problem_ncol(SEXP x);
RcppExport SEXP _prioriactions_rcpp_get_optimization_problem_ncol(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_optimization_problem_ncol(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_optimization_problem_nrow
std::size_t rcpp_get_optimization_problem_nrow(SEXP x);
RcppExport SEXP _prioriactions_rcpp_get_optimization_problem_nrow(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_optimization_problem_nrow(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_optimization_problem_ncell
std::size_t rcpp_get_optimization_problem_ncell(SEXP x);
RcppExport SEXP _prioriactions_rcpp_get_optimization_problem_ncell(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_optimization_problem_ncell(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_get_optimization_problem_A
Rcpp::List rcpp_get_optimization_problem_A(SEXP x);
RcppExport SEXP _prioriactions_rcpp_get_optimization_problem_A(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_get_optimization_problem_A(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_action_locks
bool rcpp_add_action_locks(SEXP x, Rcpp::DataFrame dist_actions_data);
RcppExport SEXP _prioriactions_rcpp_add_action_locks(SEXP xSEXP, SEXP dist_actions_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_action_locks(x, dist_actions_data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_base_variables
Rcpp::List rcpp_add_base_variables(SEXP x, Rcpp::DataFrame pu_data, Rcpp::DataFrame dist_actions_data, Rcpp::DataFrame dist_features_data, bool add_z);
RcppExport SEXP _prioriactions_rcpp_add_base_variables(SEXP xSEXP, SEXP pu_dataSEXP, SEXP dist_actions_dataSEXP, SEXP dist_features_dataSEXP, SEXP add_zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< bool >::type add_z(add_zSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_base_variables(x, pu_data, dist_actions_data, dist_features_data, add_z));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_exclude_conservation_when_actions
Rcpp::List rcpp_add_exclude_conservation_when_actions(SEXP x, Rcpp::DataFrame dist_features_data, Rcpp::DataFrame dist_actions_data, Rcpp::DataFrame dist_effects_data, SEXP benefit_col_sexp, double tol);
RcppExport SEXP _prioriactions_rcpp_add_exclude_conservation_when_actions(SEXP xSEXP, SEXP dist_features_dataSEXP, SEXP dist_actions_dataSEXP, SEXP dist_effects_dataSEXP, SEXP benefit_col_sexpSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_effects_data(dist_effects_dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type benefit_col_sexp(benefit_col_sexpSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_exclude_conservation_when_actions(x, dist_features_data, dist_actions_data, dist_effects_data, benefit_col_sexp, tol));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_linear_constraint
bool rcpp_add_linear_constraint(SEXP model_ptr, IntegerVector j0, NumericVector x, std::string sense, double rhs, std::string name);
RcppExport SEXP _prioriactions_rcpp_add_linear_constraint(SEXP model_ptrSEXP, SEXP j0SEXP, SEXP xSEXP, SEXP senseSEXP, SEXP rhsSEXP, SEXP nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type j0(j0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::string >::type sense(senseSEXP);
    Rcpp::traits::input_parameter< double >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< std::string >::type name(nameSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_linear_constraint(model_ptr, j0, x, sense, rhs, name));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_linking_x_le_w
bool rcpp_add_linking_x_le_w(SEXP x, Rcpp::DataFrame dist_actions_data);
RcppExport SEXP _prioriactions_rcpp_add_linking_x_le_w(SEXP xSEXP, SEXP dist_actions_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_linking_x_le_w(x, dist_actions_data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_linking_z_le_w
Rcpp::List rcpp_add_linking_z_le_w(SEXP x, Rcpp::DataFrame dist_features_data);
RcppExport SEXP _prioriactions_rcpp_add_linking_z_le_w(SEXP xSEXP, SEXP dist_features_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_features_data(dist_features_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_linking_z_le_w(x, dist_features_data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_pu_locks
bool rcpp_add_pu_locks(SEXP x, Rcpp::DataFrame pu_data);
RcppExport SEXP _prioriactions_rcpp_add_pu_locks(SEXP xSEXP, SEXP pu_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type pu_data(pu_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_pu_locks(x, pu_data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_target_conservation
Rcpp::List rcpp_add_target_conservation(SEXP x, Rcpp::DataFrame features_data, Rcpp::DataFrame dist_features_data, SEXP target_col_sexp, double tol);
RcppExport SEXP _prioriactions_rcpp_add_target_conservation(SEXP xSEXP, SEXP features_dataSEXP, SEXP dist_features_dataSEXP, SEXP target_col_sexpSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type features_data(features_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type target_col_sexp(target_col_sexpSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_target_conservation(x, features_data, dist_features_data, target_col_sexp, tol));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_target_mixed_total
Rcpp::List rcpp_add_target_mixed_total(SEXP x, Rcpp::DataFrame features_data, Rcpp::DataFrame dist_features_data, Rcpp::DataFrame dist_benefit_data, Rcpp::DataFrame dist_actions_data, SEXP target_col_sexp, double tol);
RcppExport SEXP _prioriactions_rcpp_add_target_mixed_total(SEXP xSEXP, SEXP features_dataSEXP, SEXP dist_features_dataSEXP, SEXP dist_benefit_dataSEXP, SEXP dist_actions_dataSEXP, SEXP target_col_sexpSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type features_data(features_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_benefit_data(dist_benefit_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type target_col_sexp(target_col_sexpSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_target_mixed_total(x, features_data, dist_features_data, dist_benefit_data, dist_actions_data, target_col_sexp, tol));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_target_mixed_total_power
Rcpp::List rcpp_add_target_mixed_total_power(SEXP x, Rcpp::DataFrame dist_features_data, Rcpp::DataFrame dist_actions_data, Rcpp::DataFrame dist_benefit_data, Rcpp::DataFrame targets_df, double exponent, int segments, SEXP amount_col_sexp, double tol);
RcppExport SEXP _prioriactions_rcpp_add_target_mixed_total_power(SEXP xSEXP, SEXP dist_features_dataSEXP, SEXP dist_actions_dataSEXP, SEXP dist_benefit_dataSEXP, SEXP targets_dfSEXP, SEXP exponentSEXP, SEXP segmentsSEXP, SEXP amount_col_sexpSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_benefit_data(dist_benefit_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type targets_df(targets_dfSEXP);
    Rcpp::traits::input_parameter< double >::type exponent(exponentSEXP);
    Rcpp::traits::input_parameter< int >::type segments(segmentsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type amount_col_sexp(amount_col_sexpSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_target_mixed_total_power(x, dist_features_data, dist_actions_data, dist_benefit_data, targets_df, exponent, segments, amount_col_sexp, tol));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_target_recovery
Rcpp::List rcpp_add_target_recovery(SEXP x, Rcpp::DataFrame features_data, Rcpp::DataFrame dist_actions_data, Rcpp::DataFrame dist_benefit_data, SEXP target_col_sexp, double tol);
RcppExport SEXP _prioriactions_rcpp_add_target_recovery(SEXP xSEXP, SEXP features_dataSEXP, SEXP dist_actions_dataSEXP, SEXP dist_benefit_dataSEXP, SEXP target_col_sexpSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type features_data(features_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_benefit_data(dist_benefit_dataSEXP);
    Rcpp::traits::input_parameter< SEXP >::type target_col_sexp(target_col_sexpSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_target_recovery(x, features_data, dist_actions_data, dist_benefit_data, target_col_sexp, tol));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_add_target_recovery_power
Rcpp::List rcpp_add_target_recovery_power(SEXP x, Rcpp::DataFrame features_data, Rcpp::DataFrame dist_actions_data, Rcpp::DataFrame dist_benefit_data, double exponent, int segments, SEXP target_col_sexp, double tol);
RcppExport SEXP _prioriactions_rcpp_add_target_recovery_power(SEXP xSEXP, SEXP features_dataSEXP, SEXP dist_actions_dataSEXP, SEXP dist_benefit_dataSEXP, SEXP exponentSEXP, SEXP segmentsSEXP, SEXP target_col_sexpSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type features_data(features_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_benefit_data(dist_benefit_dataSEXP);
    Rcpp::traits::input_parameter< double >::type exponent(exponentSEXP);
    Rcpp::traits::input_parameter< int >::type segments(segmentsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type target_col_sexp(target_col_sexpSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_add_target_recovery_power(x, features_data, dist_actions_data, dist_benefit_data, exponent, segments, target_col_sexp, tol));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_constraint_activation
bool rcpp_constraint_activation(SEXP x, DataFrame pu_data, DataFrame threats_data, DataFrame dist_threats_data);
RcppExport SEXP _prioriactions_rcpp_constraint_activation(SEXP xSEXP, SEXP pu_dataSEXP, SEXP threats_dataSEXP, SEXP dist_threats_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type threats_data(threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_constraint_activation(x, pu_data, threats_data, dist_threats_data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_constraint_benefit
bool rcpp_constraint_benefit(SEXP x, DataFrame pu_data, DataFrame features_data, DataFrame dist_features_data, DataFrame threats_data, DataFrame dist_threats_data, DataFrame sensitivity_data);
RcppExport SEXP _prioriactions_rcpp_constraint_benefit(SEXP xSEXP, SEXP pu_dataSEXP, SEXP features_dataSEXP, SEXP dist_features_dataSEXP, SEXP threats_dataSEXP, SEXP dist_threats_dataSEXP, SEXP sensitivity_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type features_data(features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type threats_data(threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type sensitivity_data(sensitivity_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_constraint_benefit(x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, sensitivity_data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_constraint_budget
bool rcpp_constraint_budget(SEXP x, DataFrame pu_data, DataFrame dist_threats_data, double budget);
RcppExport SEXP _prioriactions_rcpp_constraint_budget(SEXP xSEXP, SEXP pu_dataSEXP, SEXP dist_threats_dataSEXP, SEXP budgetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    Rcpp::traits::input_parameter< double >::type budget(budgetSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_constraint_budget(x, pu_data, dist_threats_data, budget));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_constraint_lock
bool rcpp_constraint_lock(SEXP x, DataFrame pu_data, DataFrame dist_threats_data);
RcppExport SEXP _prioriactions_rcpp_constraint_lock(SEXP xSEXP, SEXP pu_dataSEXP, SEXP dist_threats_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_constraint_lock(x, pu_data, dist_threats_data));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_constraint_target
bool rcpp_constraint_target(SEXP x, DataFrame pu_data, DataFrame features_data, DataFrame dist_features_data, DataFrame dist_threats_data, DataFrame threats_data, DataFrame sensitivity_data, int curve);
RcppExport SEXP _prioriactions_rcpp_constraint_target(SEXP xSEXP, SEXP pu_dataSEXP, SEXP features_dataSEXP, SEXP dist_features_dataSEXP, SEXP dist_threats_dataSEXP, SEXP threats_dataSEXP, SEXP sensitivity_dataSEXP, SEXP curveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type features_data(features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type threats_data(threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type sensitivity_data(sensitivity_dataSEXP);
    Rcpp::traits::input_parameter< int >::type curve(curveSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_constraint_target(x, pu_data, features_data, dist_features_data, dist_threats_data, threats_data, sensitivity_data, curve));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_fix_z_ineligible_by_positive_delta
Rcpp::List rcpp_fix_z_ineligible_by_positive_delta(SEXP x, Rcpp::DataFrame dist_features_data, Rcpp::DataFrame dist_benefit_data, bool fix_lb_too, double eps);
RcppExport SEXP _prioriactions_rcpp_fix_z_ineligible_by_positive_delta(SEXP xSEXP, SEXP dist_features_dataSEXP, SEXP dist_benefit_dataSEXP, SEXP fix_lb_tooSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_benefit_data(dist_benefit_dataSEXP);
    Rcpp::traits::input_parameter< bool >::type fix_lb_too(fix_lb_tooSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_fix_z_ineligible_by_positive_delta(x, dist_features_data, dist_benefit_data, fix_lb_too, eps));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_objective_max_coverage
bool rcpp_objective_max_coverage(SEXP x, DataFrame pu_data, DataFrame features_data, DataFrame dist_features_data, DataFrame threats_data, DataFrame dist_threats_data, DataFrame boundary_data, double blm, int curve);
RcppExport SEXP _prioriactions_rcpp_objective_max_coverage(SEXP xSEXP, SEXP pu_dataSEXP, SEXP features_dataSEXP, SEXP dist_features_dataSEXP, SEXP threats_dataSEXP, SEXP dist_threats_dataSEXP, SEXP boundary_dataSEXP, SEXP blmSEXP, SEXP curveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type features_data(features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type threats_data(threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type boundary_data(boundary_dataSEXP);
    Rcpp::traits::input_parameter< double >::type blm(blmSEXP);
    Rcpp::traits::input_parameter< int >::type curve(curveSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_objective_max_coverage(x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, boundary_data, blm, curve));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_objective_min_set
bool rcpp_objective_min_set(SEXP x, DataFrame pu_data, DataFrame features_data, DataFrame dist_features_data, DataFrame threats_data, DataFrame dist_threats_data, DataFrame boundary_data, double blm, int curve);
RcppExport SEXP _prioriactions_rcpp_objective_min_set(SEXP xSEXP, SEXP pu_dataSEXP, SEXP features_dataSEXP, SEXP dist_features_dataSEXP, SEXP threats_dataSEXP, SEXP dist_threats_dataSEXP, SEXP boundary_dataSEXP, SEXP blmSEXP, SEXP curveSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type features_data(features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type threats_data(threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type boundary_data(boundary_dataSEXP);
    Rcpp::traits::input_parameter< double >::type blm(blmSEXP);
    Rcpp::traits::input_parameter< int >::type curve(curveSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_objective_min_set(x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, boundary_data, blm, curve));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_set_objective_max_benefit
bool rcpp_set_objective_max_benefit(SEXP x, Rcpp::DataFrame dist_actions_data, Rcpp::DataFrame dist_benefit_data, std::string benefit_col);
RcppExport SEXP _prioriactions_rcpp_set_objective_max_benefit(SEXP xSEXP, SEXP dist_actions_dataSEXP, SEXP dist_benefit_dataSEXP, SEXP benefit_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_benefit_data(dist_benefit_dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type benefit_col(benefit_colSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_set_objective_max_benefit(x, dist_actions_data, dist_benefit_data, benefit_col));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_set_objective_max_net_profit
bool rcpp_set_objective_max_net_profit(SEXP x, Rcpp::DataFrame pu_data, Rcpp::DataFrame dist_actions_data, Rcpp::DataFrame dist_profit_data, std::string profit_col, bool include_pu_cost, bool include_action_cost);
RcppExport SEXP _prioriactions_rcpp_set_objective_max_net_profit(SEXP xSEXP, SEXP pu_dataSEXP, SEXP dist_actions_dataSEXP, SEXP dist_profit_dataSEXP, SEXP profit_colSEXP, SEXP include_pu_costSEXP, SEXP include_action_costSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_profit_data(dist_profit_dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type profit_col(profit_colSEXP);
    Rcpp::traits::input_parameter< bool >::type include_pu_cost(include_pu_costSEXP);
    Rcpp::traits::input_parameter< bool >::type include_action_cost(include_action_costSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_set_objective_max_net_profit(x, pu_data, dist_actions_data, dist_profit_data, profit_col, include_pu_cost, include_action_cost));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_set_objective_max_profit
bool rcpp_set_objective_max_profit(SEXP x, Rcpp::DataFrame dist_actions_data, Rcpp::DataFrame dist_profit_data, std::string profit_col);
RcppExport SEXP _prioriactions_rcpp_set_objective_max_profit(SEXP xSEXP, SEXP dist_actions_dataSEXP, SEXP dist_profit_dataSEXP, SEXP profit_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_profit_data(dist_profit_dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type profit_col(profit_colSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_set_objective_max_profit(x, dist_actions_data, dist_profit_data, profit_col));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_set_objective_max_representation
bool rcpp_set_objective_max_representation(SEXP x, Rcpp::DataFrame dist_features_data, std::string amount_col);
RcppExport SEXP _prioriactions_rcpp_set_objective_max_representation(SEXP xSEXP, SEXP dist_features_dataSEXP, SEXP amount_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type amount_col(amount_colSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_set_objective_max_representation(x, dist_features_data, amount_col));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_set_objective_min_cost
bool rcpp_set_objective_min_cost(SEXP x, Rcpp::DataFrame pu_data, Rcpp::DataFrame dist_actions_data, bool include_pu_cost, bool include_action_cost);
RcppExport SEXP _prioriactions_rcpp_set_objective_min_cost(SEXP xSEXP, SEXP pu_dataSEXP, SEXP dist_actions_dataSEXP, SEXP include_pu_costSEXP, SEXP include_action_costSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    Rcpp::traits::input_parameter< bool >::type include_pu_cost(include_pu_costSEXP);
    Rcpp::traits::input_parameter< bool >::type include_action_cost(include_action_costSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_set_objective_min_cost(x, pu_data, dist_actions_data, include_pu_cost, include_action_cost));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_set_objective_min_loss
bool rcpp_set_objective_min_loss(SEXP x, Rcpp::DataFrame dist_actions_data, Rcpp::DataFrame dist_effects_data, std::string loss_col);
RcppExport SEXP _prioriactions_rcpp_set_objective_min_loss(SEXP xSEXP, SEXP dist_actions_dataSEXP, SEXP dist_effects_dataSEXP, SEXP loss_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_actions_data(dist_actions_dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type dist_effects_data(dist_effects_dataSEXP);
    Rcpp::traits::input_parameter< std::string >::type loss_col(loss_colSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_set_objective_min_loss(x, dist_actions_data, dist_effects_data, loss_col));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_stats_benefit
DataFrame rcpp_stats_benefit(DataFrame pu_data, DataFrame features_data, DataFrame dist_features_data, DataFrame threats_data, DataFrame dist_threats_data, DataFrame sensitivity_data, std::vector<double> solution);
RcppExport SEXP _prioriactions_rcpp_stats_benefit(SEXP pu_dataSEXP, SEXP features_dataSEXP, SEXP dist_features_dataSEXP, SEXP threats_dataSEXP, SEXP dist_threats_dataSEXP, SEXP sensitivity_dataSEXP, SEXP solutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type features_data(features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type threats_data(threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type sensitivity_data(sensitivity_dataSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type solution(solutionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_stats_benefit(pu_data, features_data, dist_features_data, threats_data, dist_threats_data, sensitivity_data, solution));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_stats_connectivity_actions
NumericVector rcpp_stats_connectivity_actions(DataFrame pu_data, DataFrame threats_data, DataFrame dist_threats_data, DataFrame boundary_data, std::vector<double> solution);
RcppExport SEXP _prioriactions_rcpp_stats_connectivity_actions(SEXP pu_dataSEXP, SEXP threats_dataSEXP, SEXP dist_threats_dataSEXP, SEXP boundary_dataSEXP, SEXP solutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type threats_data(threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type boundary_data(boundary_dataSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type solution(solutionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_stats_connectivity_actions(pu_data, threats_data, dist_threats_data, boundary_data, solution));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_stats_connectivity_units
double rcpp_stats_connectivity_units(DataFrame pu_data, DataFrame boundary_data, DataFrame dist_threats_data, DataFrame dist_features_data, std::vector<double> solution);
RcppExport SEXP _prioriactions_rcpp_stats_connectivity_units(SEXP pu_dataSEXP, SEXP boundary_dataSEXP, SEXP dist_threats_dataSEXP, SEXP dist_features_dataSEXP, SEXP solutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type boundary_data(boundary_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type solution(solutionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_stats_connectivity_units(pu_data, boundary_data, dist_threats_data, dist_features_data, solution));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_stats_costs_actions
NumericVector rcpp_stats_costs_actions(DataFrame pu_data, DataFrame threats_data, DataFrame dist_threats_data, std::vector<double> solution);
RcppExport SEXP _prioriactions_rcpp_stats_costs_actions(SEXP pu_dataSEXP, SEXP threats_dataSEXP, SEXP dist_threats_dataSEXP, SEXP solutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type threats_data(threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type solution(solutionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_stats_costs_actions(pu_data, threats_data, dist_threats_data, solution));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_stats_costs_units
double rcpp_stats_costs_units(DataFrame pu_data, std::vector<double> solution);
RcppExport SEXP _prioriactions_rcpp_stats_costs_units(SEXP pu_dataSEXP, SEXP solutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type solution(solutionSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_stats_costs_units(pu_data, solution));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_stats_recovery
List rcpp_stats_recovery(std::vector<double> solution, DataFrame pu_data, DataFrame features_data, DataFrame dist_features_data, DataFrame dist_threats_data, DataFrame threats_data, DataFrame sensitivity_data);
RcppExport SEXP _prioriactions_rcpp_stats_recovery(SEXP solutionSEXP, SEXP pu_dataSEXP, SEXP features_dataSEXP, SEXP dist_features_dataSEXP, SEXP dist_threats_dataSEXP, SEXP threats_dataSEXP, SEXP sensitivity_dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type solution(solutionSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type pu_data(pu_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type features_data(features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_features_data(dist_features_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type dist_threats_data(dist_threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type threats_data(threats_dataSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type sensitivity_data(sensitivity_dataSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_stats_recovery(solution, pu_data, features_data, dist_features_data, dist_threats_data, threats_data, sensitivity_data));
    return rcpp_result_gen;
END_RCPP
}
