#' @include internal.R
NULL

#' Targets API
#'
#' @description
#' Functions to define feature-level targets for a planning problem. Targets are stored in
#' \code{x$data$targets} and later translated into mathematical constraints when the optimization
#' model is built.
#'
#' Targets are interpreted over contributions generated by selected actions. By default,
#' all actions count toward target achievement. Optionally, users can restrict which actions
#' count by providing a \code{subset} specification. This specification can contain:
#' \itemize{
#'   \item action ids,
#'   \item action-set labels stored in \code{x$data$actions$action_set},
#'   \item or a mixture of both.
#' }
#'
#' Each target is stored as a row with at least:
#' \code{feature}, \code{sense}, \code{target_unit}, \code{target_raw}, \code{basis_total},
#' \code{target_value}, and optional metadata such as \code{label}, \code{created_at},
#' and \code{subset}.
#'
#' @details
#' \strong{Targets format.}
#' The \code{targets} argument can be provided in multiple equivalent ways (as implemented by
#' \code{.pa_parse_targets()}), typically including:
#' \itemize{
#'   \item a single numeric value recycled to all features,
#'   \item a numeric vector aligned to the feature order,
#'   \item a named numeric vector where names identify features,
#'   \item a \code{data.frame} with feature identifiers and target values.
#' }
#' Features may be identified by numeric \code{id} and/or by a feature name column if supported by
#' \code{.pa_parse_targets()}.
#'
#' \strong{Absolute vs relative targets.}
#' Absolute targets set \code{target_value} directly from the provided \code{targets}.
#' Relative targets treat \code{targets} as proportions in \eqn{[0,1]} and convert them to absolute
#' thresholds using the current total amount of each feature in the landscape
#' (via \code{.pa_feature_totals()}).
#'
#' The chosen basis is stored in \code{basis_total}, and the resulting absolute threshold is stored in
#' \code{target_value}.
#'
#' \strong{Subset semantics.}
#' The \code{subset} argument does not change the target value itself. Instead, it determines
#' which actions are allowed to contribute toward achieving the target when the model is built.
#' If \code{subset = NULL}, all actions are counted.
#'
#' \strong{Overwrite behavior.}
#' When \code{overwrite=TRUE}, existing targets for the same feature(s) and subset specification
#' can be replaced. When \code{overwrite=FALSE}, overlapping rows are appended and any conflict
#' handling is delegated to \code{.pa_store_targets()}.
#'
#' @name targets
#' @keywords internal
NULL

#' @title Add absolute targets
#'
#' @description
#' Add feature-level absolute targets to a planning problem.
#'
#' These targets are stored in \code{x$data$targets} and later translated into
#' linear constraints when the optimization model is built.
#'
#' Absolute targets are interpreted directly in the same units as the underlying
#' feature contributions used by the model.
#'
#' @details
#' The \code{targets} argument is parsed by \code{.pa_parse_targets()} and can be
#' supplied in several equivalent forms, including:
#' \itemize{
#'   \item a single numeric value recycled to all features,
#'   \item a numeric vector aligned to feature order,
#'   \item a named numeric vector where names identify features,
#'   \item a \code{data.frame} with \code{feature} and \code{target} columns.
#' }
#'
#' The \code{subset} argument optionally restricts which actions count toward target
#' achievement. It may contain action ids, values of \code{action_set}, or a mixture
#' of both. If \code{NULL}, all actions count.
#'
#' Targets are stored internally with:
#' \itemize{
#'   \item \code{type = "actions"},
#'   \item \code{target_unit = "absolute"},
#'   \item \code{target_raw = target_value},
#'   \item \code{basis_total = NA}.
#' }
#'
#' @param x A \code{Data} object.
#' @param targets Target specification. See Details.
#' @param subset Optional character vector indicating which actions count toward
#'   target achievement. Entries may match action ids, \code{action_set} labels,
#'   or both. If \code{NULL}, all actions count.
#' @param overwrite Logical. If \code{TRUE}, replace existing targets for the same
#'   feature/subset combination. If \code{FALSE}, new rows are appended and any
#'   overlap is handled by \code{.pa_store_targets()}.
#' @param label Optional character label stored with the targets for reporting
#'   and bookkeeping.
#'
#' @return Updated \code{Data} object.
#'
#' @examples
#' \dontrun{
#' # Same absolute target for all features
#' p <- add_targets_absolute(p, 10)
#'
#' # Different targets by feature id
#' p <- add_targets_absolute(
#'   p,
#'   c("1" = 5, "2" = 8, "3" = 12)
#' )
#'
#' # Only actions in the "recovery" set count
#' p <- add_targets_absolute(p, 5, subset = "recovery")
#'
#' # Mix action sets and individual actions
#' p <- add_targets_absolute(p, 5, subset = c("recovery", "conservation_action"))
#' }
#'
#' @seealso [add_targets_relative()]
#' @export
add_targets_absolute <- function(x, targets,
                                 subset = NULL,
                                 overwrite = FALSE,
                                 label = NULL) {
  stopifnot(inherits(x, "Data"))

  x <- .pa_clone_data(x)
  dt <- .pa_parse_targets(x, targets)

  subset_txt <- .pa_subset_to_string(subset)

  out <- data.frame(
    feature      = as.numeric(dt$feature),
    type         = "actions",
    sense        = "ge",
    target_unit  = "absolute",
    target_raw   = as.numeric(dt$target_raw),
    basis_total  = NA_real_,
    target_value = as.numeric(dt$target_raw),
    subset       = subset_txt,
    label        = if (is.null(label)) NA_character_ else as.character(label),
    created_at   = as.character(Sys.time()),
    stringsAsFactors = FALSE
  )

  x$data$meta$model_dirty <- TRUE
  .pa_store_targets(x, out, overwrite = overwrite)
}

#' @title Add relative targets
#'
#' @description
#' Add feature-level relative targets to a planning problem.
#'
#' These targets are stored in \code{x$data$targets} and later translated into
#' linear constraints when the optimization model is built.
#'
#' Relative targets are supplied as proportions in \eqn{[0,1]} and are converted
#' internally to absolute thresholds using the current total amount of each feature
#' in the landscape (via \code{.pa_feature_totals()}).
#'
#' @details
#' The \code{targets} argument is parsed by \code{.pa_parse_targets()} and can be
#' supplied in several equivalent forms, including:
#' \itemize{
#'   \item a single numeric value recycled to all features,
#'   \item a numeric vector aligned to feature order,
#'   \item a named numeric vector where names identify features,
#'   \item a \code{data.frame} with \code{feature} and \code{target} columns.
#' }
#'
#' Relative targets must lie in \eqn{[0,1]}.
#'
#' The \code{subset} argument optionally restricts which actions count toward target
#' achievement. It may contain action ids, values of \code{action_set}, or a mixture
#' of both. If \code{NULL}, all actions count.
#'
#' Relative targets are always transformed using \code{.pa_feature_totals()}.
#' The resulting basis is stored in \code{basis_total}, and the absolute threshold
#' is stored in \code{target_value}.
#'
#' @param x A \code{Data} object.
#' @param targets Target specification as proportions in \eqn{[0,1]}. See Details.
#' @param subset Optional character vector indicating which actions count toward
#'   target achievement. Entries may match action ids, \code{action_set} labels,
#'   or both. If \code{NULL}, all actions count.
#' @param overwrite Logical. If \code{TRUE}, replace existing targets for the same
#'   feature/subset combination. If \code{FALSE}, new rows are appended and any
#'   overlap is handled by \code{.pa_store_targets()}.
#' @param label Optional character label stored with the targets for reporting
#'   and bookkeeping.
#'
#' @return Updated \code{Data} object.
#'
#' @examples
#' \dontrun{
#' # Require 30% of current feature totals for all features
#' p <- add_targets_relative(p, 0.3)
#'
#' # Require 20% of current feature totals, counting only recovery actions
#' p <- add_targets_relative(p, 0.2, subset = "recovery")
#'
#' # Require 50% of current feature totals, counting a mix of groups/actions
#' p <- add_targets_relative(p, 0.5, subset = c("recovery", "conservation_action"))
#' }
#'
#' @seealso [add_targets_absolute()]
#' @export
add_targets_relative <- function(x, targets,
                                 subset = NULL,
                                 overwrite = FALSE,
                                 label = NULL) {
  stopifnot(inherits(x, "Data"))

  x <- .pa_clone_data(x)
  dt <- .pa_parse_targets(x, targets)

  rel <- as.numeric(dt$target_raw)
  if (any(rel < 0 | rel > 1, na.rm = TRUE)) {
    stop("Relative targets must be between 0 and 1.", call. = FALSE)
  }

  basis <- .pa_feature_totals(x)
  basis_v <- basis[as.character(dt$feature)]
  basis_v[is.na(basis_v)] <- 0
  abs_target <- rel * as.numeric(basis_v)

  subset_txt <- .pa_subset_to_string(subset)

  out <- data.frame(
    feature      = as.numeric(dt$feature),
    type         = "actions",
    sense        = "ge",
    target_unit  = "relative_baseline",
    target_raw   = rel,
    basis_total  = as.numeric(basis_v),
    target_value = as.numeric(abs_target),
    subset       = subset_txt,
    label        = if (is.null(label)) NA_character_ else as.character(label),
    created_at   = as.character(Sys.time()),
    stringsAsFactors = FALSE
  )

  x$data$meta$model_dirty <- TRUE
  .pa_store_targets(x, out, overwrite = overwrite)
}
