# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_new_optimization_problem <- function(nrow = 1000000L, ncol = 1000000L, ncell = 100000L) {
    .Call(`_prioriactions_rcpp_new_optimization_problem`, nrow, ncol, ncell)
}

rcpp_optimization_problem_as_list <- function(x) {
    .Call(`_prioriactions_rcpp_optimization_problem_as_list`, x)
}

rcpp_get_optimization_problem_ncol <- function(x) {
    .Call(`_prioriactions_rcpp_get_optimization_problem_ncol`, x)
}

rcpp_get_optimization_problem_nrow <- function(x) {
    .Call(`_prioriactions_rcpp_get_optimization_problem_nrow`, x)
}

rcpp_get_optimization_problem_ncell <- function(x) {
    .Call(`_prioriactions_rcpp_get_optimization_problem_ncell`, x)
}

rcpp_get_optimization_problem_A <- function(x) {
    .Call(`_prioriactions_rcpp_get_optimization_problem_A`, x)
}

rcpp_add_action_locks <- function(x, dist_actions_data) {
    .Call(`_prioriactions_rcpp_add_action_locks`, x, dist_actions_data)
}

rcpp_add_base_variables <- function(x, pu_data, dist_actions_data, dist_features_data, add_z = TRUE) {
    .Call(`_prioriactions_rcpp_add_base_variables`, x, pu_data, dist_actions_data, dist_features_data, add_z)
}

rcpp_add_exclude_conservation_when_actions <- function(x, dist_features_data, dist_actions_data, dist_effects_data, benefit_col_sexp = NULL, tol = 1e-12) {
    .Call(`_prioriactions_rcpp_add_exclude_conservation_when_actions`, x, dist_features_data, dist_actions_data, dist_effects_data, benefit_col_sexp, tol)
}

rcpp_add_linear_constraint <- function(model_ptr, j0, x, sense, rhs, name = "") {
    .Call(`_prioriactions_rcpp_add_linear_constraint`, model_ptr, j0, x, sense, rhs, name)
}

rcpp_add_linking_x_le_w <- function(x, dist_actions_data) {
    .Call(`_prioriactions_rcpp_add_linking_x_le_w`, x, dist_actions_data)
}

rcpp_add_linking_z_le_w <- function(x, dist_features_data) {
    .Call(`_prioriactions_rcpp_add_linking_z_le_w`, x, dist_features_data)
}

rcpp_add_pu_locks <- function(x, pu_data) {
    .Call(`_prioriactions_rcpp_add_pu_locks`, x, pu_data)
}

rcpp_add_target_conservation <- function(x, features_data, dist_features_data, target_col_sexp = NULL, tol = 1e-12) {
    .Call(`_prioriactions_rcpp_add_target_conservation`, x, features_data, dist_features_data, target_col_sexp, tol)
}

rcpp_add_target_mixed_total <- function(x, features_data, dist_features_data, dist_benefit_data, dist_actions_data, target_col_sexp = NULL, tol = 1e-12) {
    .Call(`_prioriactions_rcpp_add_target_mixed_total`, x, features_data, dist_features_data, dist_benefit_data, dist_actions_data, target_col_sexp, tol)
}

rcpp_add_target_mixed_total_power <- function(x, dist_features_data, dist_actions_data, dist_benefit_data, targets_df, exponent = 2.0, segments = 6L, amount_col_sexp = NULL, tol = 1e-12) {
    .Call(`_prioriactions_rcpp_add_target_mixed_total_power`, x, dist_features_data, dist_actions_data, dist_benefit_data, targets_df, exponent, segments, amount_col_sexp, tol)
}

rcpp_add_target_recovery <- function(x, features_data, dist_actions_data, dist_benefit_data, target_col_sexp = NULL, tol = 1e-12) {
    .Call(`_prioriactions_rcpp_add_target_recovery`, x, features_data, dist_actions_data, dist_benefit_data, target_col_sexp, tol)
}

rcpp_add_target_recovery_power <- function(x, features_data, dist_actions_data, dist_benefit_data, exponent = 2.0, segments = 3L, target_col_sexp = NULL, tol = 1e-12) {
    .Call(`_prioriactions_rcpp_add_target_recovery_power`, x, features_data, dist_actions_data, dist_benefit_data, exponent, segments, target_col_sexp, tol)
}

rcpp_constraint_activation <- function(x, pu_data, threats_data, dist_threats_data) {
    .Call(`_prioriactions_rcpp_constraint_activation`, x, pu_data, threats_data, dist_threats_data)
}

rcpp_constraint_benefit <- function(x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, sensitivity_data) {
    .Call(`_prioriactions_rcpp_constraint_benefit`, x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, sensitivity_data)
}

rcpp_constraint_budget <- function(x, pu_data, dist_threats_data, budget) {
    .Call(`_prioriactions_rcpp_constraint_budget`, x, pu_data, dist_threats_data, budget)
}

rcpp_constraint_lock <- function(x, pu_data, dist_threats_data) {
    .Call(`_prioriactions_rcpp_constraint_lock`, x, pu_data, dist_threats_data)
}

rcpp_constraint_target <- function(x, pu_data, features_data, dist_features_data, dist_threats_data, threats_data, sensitivity_data, curve) {
    .Call(`_prioriactions_rcpp_constraint_target`, x, pu_data, features_data, dist_features_data, dist_threats_data, threats_data, sensitivity_data, curve)
}

rcpp_fix_z_ineligible_by_positive_delta <- function(x, dist_features_data, dist_benefit_data, fix_lb_too = TRUE, eps = 1e-12) {
    .Call(`_prioriactions_rcpp_fix_z_ineligible_by_positive_delta`, x, dist_features_data, dist_benefit_data, fix_lb_too, eps)
}

rcpp_objective_max_coverage <- function(x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, boundary_data, blm, curve) {
    .Call(`_prioriactions_rcpp_objective_max_coverage`, x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, boundary_data, blm, curve)
}

rcpp_objective_min_set <- function(x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, boundary_data, blm, curve) {
    .Call(`_prioriactions_rcpp_objective_min_set`, x, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, boundary_data, blm, curve)
}

rcpp_set_objective_max_benefit <- function(x, dist_actions_data, dist_benefit_data, benefit_col = "benefit") {
    .Call(`_prioriactions_rcpp_set_objective_max_benefit`, x, dist_actions_data, dist_benefit_data, benefit_col)
}

rcpp_set_objective_max_net_profit <- function(x, pu_data, dist_actions_data, dist_profit_data, profit_col = "profit", include_pu_cost = TRUE, include_action_cost = TRUE) {
    .Call(`_prioriactions_rcpp_set_objective_max_net_profit`, x, pu_data, dist_actions_data, dist_profit_data, profit_col, include_pu_cost, include_action_cost)
}

rcpp_set_objective_max_profit <- function(x, dist_actions_data, dist_profit_data, profit_col = "profit") {
    .Call(`_prioriactions_rcpp_set_objective_max_profit`, x, dist_actions_data, dist_profit_data, profit_col)
}

rcpp_set_objective_max_representation <- function(x, dist_features_data, amount_col = "amount") {
    .Call(`_prioriactions_rcpp_set_objective_max_representation`, x, dist_features_data, amount_col)
}

rcpp_set_objective_min_cost <- function(x, pu_data, dist_actions_data, include_pu_cost = TRUE, include_action_cost = TRUE) {
    .Call(`_prioriactions_rcpp_set_objective_min_cost`, x, pu_data, dist_actions_data, include_pu_cost, include_action_cost)
}

rcpp_set_objective_min_loss <- function(x, dist_actions_data, dist_effects_data, loss_col = "loss") {
    .Call(`_prioriactions_rcpp_set_objective_min_loss`, x, dist_actions_data, dist_effects_data, loss_col)
}

rcpp_stats_benefit <- function(pu_data, features_data, dist_features_data, threats_data, dist_threats_data, sensitivity_data, solution) {
    .Call(`_prioriactions_rcpp_stats_benefit`, pu_data, features_data, dist_features_data, threats_data, dist_threats_data, sensitivity_data, solution)
}

rcpp_stats_connectivity_actions <- function(pu_data, threats_data, dist_threats_data, boundary_data, solution) {
    .Call(`_prioriactions_rcpp_stats_connectivity_actions`, pu_data, threats_data, dist_threats_data, boundary_data, solution)
}

rcpp_stats_connectivity_units <- function(pu_data, boundary_data, dist_threats_data, dist_features_data, solution) {
    .Call(`_prioriactions_rcpp_stats_connectivity_units`, pu_data, boundary_data, dist_threats_data, dist_features_data, solution)
}

rcpp_stats_costs_actions <- function(pu_data, threats_data, dist_threats_data, solution) {
    .Call(`_prioriactions_rcpp_stats_costs_actions`, pu_data, threats_data, dist_threats_data, solution)
}

rcpp_stats_costs_units <- function(pu_data, solution) {
    .Call(`_prioriactions_rcpp_stats_costs_units`, pu_data, solution)
}

rcpp_stats_recovery <- function(solution, pu_data, features_data, dist_features_data, dist_threats_data, threats_data, sensitivity_data) {
    .Call(`_prioriactions_rcpp_stats_recovery`, solution, pu_data, features_data, dist_features_data, dist_threats_data, threats_data, sensitivity_data)
}

